#!/usr/bin/env python3

import os
DIR_THIS = os.path.dirname(os.path.abspath(__file__))


from flask import Flask
app = Flask(__name__, static_folder=f"{DIR_THIS}/www")


@app.route('/')
def route_index():
    return app.send_static_file("index.html")


@app.route('/<path:path>')
def route_all(path):
    return app.send_static_file(path)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=3333, debug=True)

